[phases.install]
cmds = [
  "npm install",
  "npx prisma generate --schema prisma/schema.prisma"
]

[phases.build]
cmds = [
  "npm install",
  "npx prisma generate --schema prisma/schema.prisma",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy --schema prisma/schema.prisma && npm run start:prod"
